name: Build and Test

on:
  push:
    branches: [ next, master ]
  pull_request:
    branches: [ next, master ]


jobs:
  # Build the library and site
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Build project
    - uses: actions/checkout@v2
      with:
        cmd: yarn install && yarn build

  # Run the test suite
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          working-directory: tests
          build: yarn build
          start: yarn test:serve
          wait-on: http://localhost:1234
